/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppHeader: typeof import('./src/components/AppHeader.vue')['default']
    ICarbonAccessibility: typeof import('~icons/carbon/accessibility')['default']
    IconCarbonAccessibility: typeof import('~icons/carbon/accessibility')['default']
    IconMaterialSymbolsLightSunnyOutline: typeof import('~icons/material-symbols-light/sunny-outline')['default']
    IMaterialSymbolsLightSunnyOutline: typeof import('~icons/material-symbols-light/sunny-outline')['default']
    MaterialSymbolsLightSunnyOutline: typeof import('./src/components/icons/MaterialSymbolsLightSunnyOutline.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
